package cn.com.sinosoft.formdesign.model;

// Generated 2015-6-1 16:50:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TFormdesignFormdata generated by hbm2java
 */
public class TFormdesignFormdata implements java.io.Serializable {

	private String id;
	private String formId;
	private byte[] formData;
	private Date dtCreate;
	private Date dtUpdate;
	private String reportUser;

	public TFormdesignFormdata() {
	}

	public TFormdesignFormdata(String id, String formId, byte[] formData,
			Date dtCreate, Date dtUpdate, String reportUser) {
		this.id = id;
		this.formId = formId;
		this.formData = formData;
		this.dtCreate = dtCreate;
		this.dtUpdate = dtUpdate;
		this.reportUser = reportUser;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFormId() {
		return this.formId;
	}

	public void setFormId(String formId) {
		this.formId = formId;
	}

	public byte[] getFormData() {
		return this.formData;
	}

	public void setFormData(byte[] formData) {
		this.formData = formData;
	}

	public Date getDtCreate() {
		return this.dtCreate;
	}

	public void setDtCreate(Date dtCreate) {
		this.dtCreate = dtCreate;
	}

	public Date getDtUpdate() {
		return this.dtUpdate;
	}

	public void setDtUpdate(Date dtUpdate) {
		this.dtUpdate = dtUpdate;
	}

	public String getReportUser() {
		return this.reportUser;
	}

	public void setReportUser(String reportUser) {
		this.reportUser = reportUser;
	}

}
