package cn.com.sinosoft.formdesign.model;

// Generated 2015-6-1 16:50:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TFormdesignForm generated by hbm2java
 */
public class TFormdesignForm implements java.io.Serializable {

	private String id;
	private String title;
	private byte[] contentSrc;
	private byte[] content;
	private Date dtCreate;
	private Date dtUpdate;
	private String isPub;
	private Date dtPub;
	private byte[] fields;
	private String createUser;

	public TFormdesignForm() {
	}

	public TFormdesignForm(String id, String title, byte[] contentSrc,
			byte[] content, Date dtCreate, Date dtUpdate, String isPub,
			String createUser) {
		this.id = id;
		this.title = title;
		this.contentSrc = contentSrc;
		this.content = content;
		this.dtCreate = dtCreate;
		this.dtUpdate = dtUpdate;
		this.isPub = isPub;
		this.createUser = createUser;
	}

	public TFormdesignForm(String id, String title, byte[] contentSrc,
			byte[] content, Date dtCreate, Date dtUpdate, String isPub,
			Date dtPub, byte[] fields, String createUser) {
		this.id = id;
		this.title = title;
		this.contentSrc = contentSrc;
		this.content = content;
		this.dtCreate = dtCreate;
		this.dtUpdate = dtUpdate;
		this.isPub = isPub;
		this.dtPub = dtPub;
		this.fields = fields;
		this.createUser = createUser;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public byte[] getContentSrc() {
		return this.contentSrc;
	}

	public void setContentSrc(byte[] contentSrc) {
		this.contentSrc = contentSrc;
	}

	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

	public Date getDtCreate() {
		return this.dtCreate;
	}

	public void setDtCreate(Date dtCreate) {
		this.dtCreate = dtCreate;
	}

	public Date getDtUpdate() {
		return this.dtUpdate;
	}

	public void setDtUpdate(Date dtUpdate) {
		this.dtUpdate = dtUpdate;
	}

	public String getIsPub() {
		return this.isPub;
	}

	public void setIsPub(String isPub) {
		this.isPub = isPub;
	}

	public Date getDtPub() {
		return this.dtPub;
	}

	public void setDtPub(Date dtPub) {
		this.dtPub = dtPub;
	}

	public byte[] getFields() {
		return this.fields;
	}

	public void setFields(byte[] fields) {
		this.fields = fields;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

}
