package cn.com.sinosoft.common.model;
// Generated 2015-8-15 12:20:10 by Hibernate Tools 3.2.2.GA



/**
 * TCode generated by hbm2java
 */
public class TCode  implements java.io.Serializable {


     private String id;
     private String codetype;
     private String codevalue;
     private int rank;

    public TCode() {
    }

    public TCode(String id, String codetype, String codevalue, int rank) {
       this.id = id;
       this.codetype = codetype;
       this.codevalue = codevalue;
       this.rank = rank;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCodetype() {
        return this.codetype;
    }
    
    public void setCodetype(String codetype) {
        this.codetype = codetype;
    }
    public String getCodevalue() {
        return this.codevalue;
    }
    
    public void setCodevalue(String codevalue) {
        this.codevalue = codevalue;
    }
    public int getRank() {
        return this.rank;
    }
    
    public void setRank(int rank) {
        this.rank = rank;
    }




}


