package cn.com.sinosoft.common.model;
// Generated 2015-8-18 0:35:05 by Hibernate Tools 3.2.2.GA



/**
 * TCodetype generated by hbm2java
 */
public class TCodetype  implements java.io.Serializable {


     private String id;
     private String codetype;
     private String codetypedesc;

    public TCodetype() {
    }

    public TCodetype(String id, String codetype, String codetypedesc) {
       this.id = id;
       this.codetype = codetype;
       this.codetypedesc = codetypedesc;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCodetype() {
        return this.codetype;
    }
    
    public void setCodetype(String codetype) {
        this.codetype = codetype;
    }
    public String getCodetypedesc() {
        return this.codetypedesc;
    }
    
    public void setCodetypedesc(String codetypedesc) {
        this.codetypedesc = codetypedesc;
    }




}


