package cn.com.sinosoft.common.model;
// Generated 2015-7-11 12:12:25 by Hibernate Tools 3.2.2.GA



/**
 * TContractData generated by hbm2java
 */
public class TContractData  implements java.io.Serializable {


     private String id;
     private String contractId;
     private String attachmentId;

    public TContractData() {
    }

    public TContractData(String id, String contractId, String attachmentId) {
       this.id = id;
       this.contractId = contractId;
       this.attachmentId = attachmentId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getContractId() {
        return this.contractId;
    }
    
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }
    public String getAttachmentId() {
        return this.attachmentId;
    }
    
    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId;
    }




}


