package cn.com.sinosoft.common.model;
// Generated 2015-8-18 0:35:05 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TCustomResume generated by hbm2java
 */
public class TCustomResume  implements java.io.Serializable {


     private String id;
     private String customId;
     private String resumeId;
     private Date createtime;
     private String createuser;
     private String state;

    public TCustomResume() {
    }

	
    public TCustomResume(String id, String customId, String resumeId, String createuser) {
        this.id = id;
        this.customId = customId;
        this.resumeId = resumeId;
        this.createuser = createuser;
    }
    public TCustomResume(String id, String customId, String resumeId, Date createtime, String createuser, String state) {
       this.id = id;
       this.customId = customId;
       this.resumeId = resumeId;
       this.createtime = createtime;
       this.createuser = createuser;
       this.state = state;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCustomId() {
        return this.customId;
    }
    
    public void setCustomId(String customId) {
        this.customId = customId;
    }
    public String getResumeId() {
        return this.resumeId;
    }
    
    public void setResumeId(String resumeId) {
        this.resumeId = resumeId;
    }
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    public String getCreateuser() {
        return this.createuser;
    }
    
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


