package cn.com.sinosoft.common.model;
// Generated 2015-7-12 11:28:57 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TCustom generated by hbm2java
 */
public class TCustom  implements java.io.Serializable {


     private String id;
     private String customName;
     private String industry;
     private String team;
     private String source;
     private String state;
     private String contactName;
     private String contactDuty;
     private String contactLandline;
     private String contactCellphone;
     private String contactFax;
     private String contactEmail;
     private String contactQq;
     private String contactWeixin;
     private String contactAddress;
     private String contactWebsite;
     private String companyProfile;
     private String createUser;
     private Date createTime;
     private String lastUpdateUser;
     private Date lastUpdateTime;

    public TCustom() {
    }

	
    public TCustom(String id, String customName, String team, String state, String contactName, String createUser) {
        this.id = id;
        this.customName = customName;
        this.team = team;
        this.state = state;
        this.contactName = contactName;
        this.createUser = createUser;
    }
    public TCustom(String id, String customName, String industry, String team, String source, String state, String contactName, String contactDuty, String contactLandline, String contactCellphone, String contactFax, String contactEmail, String contactQq, String contactWeixin, String contactAddress, String contactWebsite, String companyProfile, String createUser, Date createTime, String lastUpdateUser, Date lastUpdateTime) {
       this.id = id;
       this.customName = customName;
       this.industry = industry;
       this.team = team;
       this.source = source;
       this.state = state;
       this.contactName = contactName;
       this.contactDuty = contactDuty;
       this.contactLandline = contactLandline;
       this.contactCellphone = contactCellphone;
       this.contactFax = contactFax;
       this.contactEmail = contactEmail;
       this.contactQq = contactQq;
       this.contactWeixin = contactWeixin;
       this.contactAddress = contactAddress;
       this.contactWebsite = contactWebsite;
       this.companyProfile = companyProfile;
       this.createUser = createUser;
       this.createTime = createTime;
       this.lastUpdateUser = lastUpdateUser;
       this.lastUpdateTime = lastUpdateTime;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCustomName() {
        return this.customName;
    }
    
    public void setCustomName(String customName) {
        this.customName = customName;
    }
    public String getIndustry() {
        return this.industry;
    }
    
    public void setIndustry(String industry) {
        this.industry = industry;
    }
    public String getTeam() {
        return this.team;
    }
    
    public void setTeam(String team) {
        this.team = team;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    public String getContactDuty() {
        return this.contactDuty;
    }
    
    public void setContactDuty(String contactDuty) {
        this.contactDuty = contactDuty;
    }
    public String getContactLandline() {
        return this.contactLandline;
    }
    
    public void setContactLandline(String contactLandline) {
        this.contactLandline = contactLandline;
    }
    public String getContactCellphone() {
        return this.contactCellphone;
    }
    
    public void setContactCellphone(String contactCellphone) {
        this.contactCellphone = contactCellphone;
    }
    public String getContactFax() {
        return this.contactFax;
    }
    
    public void setContactFax(String contactFax) {
        this.contactFax = contactFax;
    }
    public String getContactEmail() {
        return this.contactEmail;
    }
    
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }
    public String getContactQq() {
        return this.contactQq;
    }
    
    public void setContactQq(String contactQq) {
        this.contactQq = contactQq;
    }
    public String getContactWeixin() {
        return this.contactWeixin;
    }
    
    public void setContactWeixin(String contactWeixin) {
        this.contactWeixin = contactWeixin;
    }
    public String getContactAddress() {
        return this.contactAddress;
    }
    
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress;
    }
    public String getContactWebsite() {
        return this.contactWebsite;
    }
    
    public void setContactWebsite(String contactWebsite) {
        this.contactWebsite = contactWebsite;
    }
    public String getCompanyProfile() {
        return this.companyProfile;
    }
    
    public void setCompanyProfile(String companyProfile) {
        this.companyProfile = companyProfile;
    }
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getLastUpdateUser() {
        return this.lastUpdateUser;
    }
    
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser;
    }
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }




}


