package cn.com.sinosoft.common.model;
// Generated 2015-7-25 14:48:24 by Hibernate Tools 3.2.2.GA



/**
 * TJobCommFile generated by hbm2java
 */
public class TJobCommFile  implements java.io.Serializable {


     private String id;
     private String attachmentId;
     private String jobId;

    public TJobCommFile() {
    }

    public TJobCommFile(String id, String attachmentId, String jobId) {
       this.id = id;
       this.attachmentId = attachmentId;
       this.jobId = jobId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getAttachmentId() {
        return this.attachmentId;
    }
    
    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId;
    }
    public String getJobId() {
        return this.jobId;
    }
    
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }




}


