package cn.com.sinosoft.common.model;
// Generated 2015-6-22 19:41:12 by Hibernate Tools 3.2.2.GA



/**
 * TResumeWorkhistory generated by hbm2java
 */
public class TResumeWorkhistory  implements java.io.Serializable {


     private String id;
     private String resumeId;
     private byte[] content;
     private String timeBegin;
     private String timeEnd;
     private String company;

    public TResumeWorkhistory() {
    }

	
    public TResumeWorkhistory(String id, String resumeId, byte[] content) {
        this.id = id;
        this.resumeId = resumeId;
        this.content = content;
    }
    public TResumeWorkhistory(String id, String resumeId, byte[] content, String timeBegin, String timeEnd, String company) {
       this.id = id;
       this.resumeId = resumeId;
       this.content = content;
       this.timeBegin = timeBegin;
       this.timeEnd = timeEnd;
       this.company = company;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getResumeId() {
        return this.resumeId;
    }
    
    public void setResumeId(String resumeId) {
        this.resumeId = resumeId;
    }
    public byte[] getContent() {
        return this.content;
    }
    
    public void setContent(byte[] content) {
        this.content = content;
    }
    public String getTimeBegin() {
        return this.timeBegin;
    }
    
    public void setTimeBegin(String timeBegin) {
        this.timeBegin = timeBegin;
    }
    public String getTimeEnd() {
        return this.timeEnd;
    }
    
    public void setTimeEnd(String timeEnd) {
        this.timeEnd = timeEnd;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }




}


