package cn.com.sinosoft.common.model;
// Generated 2015-7-25 14:48:24 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TResumeJobComm generated by hbm2java
 */
public class TResumeJobComm  implements java.io.Serializable {


     private String id;
     private Date createDate;
     private String createUser;
     private String content;
     private String resumejobId;

    public TResumeJobComm() {
    }

    public TResumeJobComm(String id, Date createDate, String createUser, String content, String resumejobId) {
       this.id = id;
       this.createDate = createDate;
       this.createUser = createUser;
       this.content = content;
       this.resumejobId = resumejobId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getResumejobId() {
        return this.resumejobId;
    }
    
    public void setResumejobId(String resumejobId) {
        this.resumejobId = resumejobId;
    }




}


