package cn.com.sinosoft.common.model;
// Generated 2015-8-15 12:20:10 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TResumeLanguage generated by hbm2java
 */
public class TResumeLanguage  implements java.io.Serializable {


     private String id;
     private String resumeId;
     private String content;
     private String lanType;
     private String readAb;
     private String listenAb;
     private Date createTime;
     private String createUser;

    public TResumeLanguage() {
    }

	
    public TResumeLanguage(String id, String resumeId) {
        this.id = id;
        this.resumeId = resumeId;
    }
    public TResumeLanguage(String id, String resumeId, String content, String lanType, String readAb, String listenAb, Date createTime, String createUser) {
       this.id = id;
       this.resumeId = resumeId;
       this.content = content;
       this.lanType = lanType;
       this.readAb = readAb;
       this.listenAb = listenAb;
       this.createTime = createTime;
       this.createUser = createUser;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getResumeId() {
        return this.resumeId;
    }
    
    public void setResumeId(String resumeId) {
        this.resumeId = resumeId;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getLanType() {
        return this.lanType;
    }
    
    public void setLanType(String lanType) {
        this.lanType = lanType;
    }
    public String getReadAb() {
        return this.readAb;
    }
    
    public void setReadAb(String readAb) {
        this.readAb = readAb;
    }
    public String getListenAb() {
        return this.listenAb;
    }
    
    public void setListenAb(String listenAb) {
        this.listenAb = listenAb;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }




}


