package cn.com.sinosoft.common.model;
// Generated 2015-6-15 21:19:57 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TResume generated by hbm2java
 */
public class TResume  implements java.io.Serializable {


     private String id;
     private String name;
     private String address;
     private String sex;
     private String education;
     private Date birthcay;
     private String marrage;
     private String phone;
     private String email;
     private String currentWage;
     private String workState;
     private byte[] desc;
     private String headImage;
     private String createUser;
     private Date createTime;
     private Date lastUpdateTime;
     private String lastUpdateUser;

    public TResume() {
    }

	
    public TResume(String id, String name, String sex, String createUser, Date createTime, Date lastUpdateTime) {
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.createUser = createUser;
        this.createTime = createTime;
        this.lastUpdateTime = lastUpdateTime;
    }
    public TResume(String id, String name, String address, String sex, String education, Date birthcay, String marrage, String phone, String email, String currentWage, String workState, byte[] desc, String headImage, String createUser, Date createTime, Date lastUpdateTime, String lastUpdateUser) {
       this.id = id;
       this.name = name;
       this.address = address;
       this.sex = sex;
       this.education = education;
       this.birthcay = birthcay;
       this.marrage = marrage;
       this.phone = phone;
       this.email = email;
       this.currentWage = currentWage;
       this.workState = workState;
       this.desc = desc;
       this.headImage = headImage;
       this.createUser = createUser;
       this.createTime = createTime;
       this.lastUpdateTime = lastUpdateTime;
       this.lastUpdateUser = lastUpdateUser;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getEducation() {
        return this.education;
    }
    
    public void setEducation(String education) {
        this.education = education;
    }
    public Date getBirthcay() {
        return this.birthcay;
    }
    
    public void setBirthcay(Date birthcay) {
        this.birthcay = birthcay;
    }
    public String getMarrage() {
        return this.marrage;
    }
    
    public void setMarrage(String marrage) {
        this.marrage = marrage;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCurrentWage() {
        return this.currentWage;
    }
    
    public void setCurrentWage(String currentWage) {
        this.currentWage = currentWage;
    }
    public String getWorkState() {
        return this.workState;
    }
    
    public void setWorkState(String workState) {
        this.workState = workState;
    }
    public byte[] getDesc() {
        return this.desc;
    }
    
    public void setDesc(byte[] desc) {
        this.desc = desc;
    }
    public String getHeadImage() {
        return this.headImage;
    }
    
    public void setHeadImage(String headImage) {
        this.headImage = headImage;
    }
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
    public String getLastUpdateUser() {
        return this.lastUpdateUser;
    }
    
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser;
    }




}


