package cn.com.sinosoft.common.model;
// Generated 2015-7-2 1:30:39 by Hibernate Tools 3.2.2.GA



/**
 * TResumeEdu generated by hbm2java
 */
public class TResumeEdu  implements java.io.Serializable {


     private String id;
     private String resumeId;
     private byte[] content;
     private String timeBegin;
     private String timeEnd;
     private String org;
     private String course;

    public TResumeEdu() {
    }

	
    public TResumeEdu(String id, String resumeId) {
        this.id = id;
        this.resumeId = resumeId;
    }
    public TResumeEdu(String id, String resumeId, byte[] content, String timeBegin, String timeEnd, String org, String course) {
       this.id = id;
       this.resumeId = resumeId;
       this.content = content;
       this.timeBegin = timeBegin;
       this.timeEnd = timeEnd;
       this.org = org;
       this.course = course;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getResumeId() {
        return this.resumeId;
    }
    
    public void setResumeId(String resumeId) {
        this.resumeId = resumeId;
    }
    public byte[] getContent() {
        return this.content;
    }
    
    public void setContent(byte[] content) {
        this.content = content;
    }
    public String getTimeBegin() {
        return this.timeBegin;
    }
    
    public void setTimeBegin(String timeBegin) {
        this.timeBegin = timeBegin;
    }
    public String getTimeEnd() {
        return this.timeEnd;
    }
    
    public void setTimeEnd(String timeEnd) {
        this.timeEnd = timeEnd;
    }
    public String getOrg() {
        return this.org;
    }
    
    public void setOrg(String org) {
        this.org = org;
    }
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }




}


