package cn.com.sinosoft.common.model;
// Generated 2015-7-19 16:35:59 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TResumeEdu generated by hbm2java
 */
public class TResumeEdu  implements java.io.Serializable {


     private String id;
     private String resumeId;
     private String content;
     private String timeBegin;
     private String timeEnd;
     private String org;
     private String course;
     private Date createTime;
     private String createUser;

    public TResumeEdu() {
    }

	
    public TResumeEdu(String id, String resumeId) {
        this.id = id;
        this.resumeId = resumeId;
    }
    public TResumeEdu(String id, String resumeId, String content, String timeBegin, String timeEnd, String org, String course, Date createTime, String createUser) {
       this.id = id;
       this.resumeId = resumeId;
       this.content = content;
       this.timeBegin = timeBegin;
       this.timeEnd = timeEnd;
       this.org = org;
       this.course = course;
       this.createTime = createTime;
       this.createUser = createUser;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getResumeId() {
        return this.resumeId;
    }
    
    public void setResumeId(String resumeId) {
        this.resumeId = resumeId;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getTimeBegin() {
        return this.timeBegin;
    }
    
    public void setTimeBegin(String timeBegin) {
        this.timeBegin = timeBegin;
    }
    public String getTimeEnd() {
        return this.timeEnd;
    }
    
    public void setTimeEnd(String timeEnd) {
        this.timeEnd = timeEnd;
    }
    public String getOrg() {
        return this.org;
    }
    
    public void setOrg(String org) {
        this.org = org;
    }
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }




}


