package cn.com.sinosoft.common.model;
// Generated 2015-7-2 1:30:39 by Hibernate Tools 3.2.2.GA



/**
 * TResumeTarget generated by hbm2java
 */
public class TResumeTarget  implements java.io.Serializable {


     private String id;
     private String resumeId;
     private String targetType;
     private String targetPlace;
     private String targetJob;
     private String targetIndustry;
     private String targetPay;
     private String workState;

    public TResumeTarget() {
    }

	
    public TResumeTarget(String id, String resumeId) {
        this.id = id;
        this.resumeId = resumeId;
    }
    public TResumeTarget(String id, String resumeId, String targetType, String targetPlace, String targetJob, String targetIndustry, String targetPay, String workState) {
       this.id = id;
       this.resumeId = resumeId;
       this.targetType = targetType;
       this.targetPlace = targetPlace;
       this.targetJob = targetJob;
       this.targetIndustry = targetIndustry;
       this.targetPay = targetPay;
       this.workState = workState;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getResumeId() {
        return this.resumeId;
    }
    
    public void setResumeId(String resumeId) {
        this.resumeId = resumeId;
    }
    public String getTargetType() {
        return this.targetType;
    }
    
    public void setTargetType(String targetType) {
        this.targetType = targetType;
    }
    public String getTargetPlace() {
        return this.targetPlace;
    }
    
    public void setTargetPlace(String targetPlace) {
        this.targetPlace = targetPlace;
    }
    public String getTargetJob() {
        return this.targetJob;
    }
    
    public void setTargetJob(String targetJob) {
        this.targetJob = targetJob;
    }
    public String getTargetIndustry() {
        return this.targetIndustry;
    }
    
    public void setTargetIndustry(String targetIndustry) {
        this.targetIndustry = targetIndustry;
    }
    public String getTargetPay() {
        return this.targetPay;
    }
    
    public void setTargetPay(String targetPay) {
        this.targetPay = targetPay;
    }
    public String getWorkState() {
        return this.workState;
    }
    
    public void setWorkState(String workState) {
        this.workState = workState;
    }




}


