package cn.com.sinosoft.common.model;
// Generated 2015-8-15 12:20:10 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * TUser generated by hbm2java
 */
public class TUser  implements java.io.Serializable {


     private String id;
     private String username;
     private String password;
     private String name;
     private String sex;
     private String duty;
     private Date entryDate;
     private String state;
     private String idCard;
     private String npPlace;
     private String phone;
     private String eduSchool;
     private Date eduDate;
     private String department;
     private String team;
     private String userType;
     private String email;
     private String msn;
     private String education;
     private String professional;
     private Date positiveDate;
     private Date leaveDate;
     private String skills;
     private String userCreate;
     private Date createTime;
     private String lastUpdateUser;
     private Date lastUpdateTime;
     private String isDisabled;

    public TUser() {
    }

	
    public TUser(String id, String username, String password, String name, String sex, String duty, String userType, Date createTime, Date lastUpdateTime, String isDisabled) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.name = name;
        this.sex = sex;
        this.duty = duty;
        this.userType = userType;
        this.createTime = createTime;
        this.lastUpdateTime = lastUpdateTime;
        this.isDisabled = isDisabled;
    }
    public TUser(String id, String username, String password, String name, String sex, String duty, Date entryDate, String state, String idCard, String npPlace, String phone, String eduSchool, Date eduDate, String department, String team, String userType, String email, String msn, String education, String professional, Date positiveDate, Date leaveDate, String skills, String userCreate, Date createTime, String lastUpdateUser, Date lastUpdateTime, String isDisabled) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.name = name;
       this.sex = sex;
       this.duty = duty;
       this.entryDate = entryDate;
       this.state = state;
       this.idCard = idCard;
       this.npPlace = npPlace;
       this.phone = phone;
       this.eduSchool = eduSchool;
       this.eduDate = eduDate;
       this.department = department;
       this.team = team;
       this.userType = userType;
       this.email = email;
       this.msn = msn;
       this.education = education;
       this.professional = professional;
       this.positiveDate = positiveDate;
       this.leaveDate = leaveDate;
       this.skills = skills;
       this.userCreate = userCreate;
       this.createTime = createTime;
       this.lastUpdateUser = lastUpdateUser;
       this.lastUpdateTime = lastUpdateTime;
       this.isDisabled = isDisabled;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getDuty() {
        return this.duty;
    }
    
    public void setDuty(String duty) {
        this.duty = duty;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getIdCard() {
        return this.idCard;
    }
    
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }
    public String getNpPlace() {
        return this.npPlace;
    }
    
    public void setNpPlace(String npPlace) {
        this.npPlace = npPlace;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEduSchool() {
        return this.eduSchool;
    }
    
    public void setEduSchool(String eduSchool) {
        this.eduSchool = eduSchool;
    }
    public Date getEduDate() {
        return this.eduDate;
    }
    
    public void setEduDate(Date eduDate) {
        this.eduDate = eduDate;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getTeam() {
        return this.team;
    }
    
    public void setTeam(String team) {
        this.team = team;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMsn() {
        return this.msn;
    }
    
    public void setMsn(String msn) {
        this.msn = msn;
    }
    public String getEducation() {
        return this.education;
    }
    
    public void setEducation(String education) {
        this.education = education;
    }
    public String getProfessional() {
        return this.professional;
    }
    
    public void setProfessional(String professional) {
        this.professional = professional;
    }
    public Date getPositiveDate() {
        return this.positiveDate;
    }
    
    public void setPositiveDate(Date positiveDate) {
        this.positiveDate = positiveDate;
    }
    public Date getLeaveDate() {
        return this.leaveDate;
    }
    
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }
    public String getSkills() {
        return this.skills;
    }
    
    public void setSkills(String skills) {
        this.skills = skills;
    }
    public String getUserCreate() {
        return this.userCreate;
    }
    
    public void setUserCreate(String userCreate) {
        this.userCreate = userCreate;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getLastUpdateUser() {
        return this.lastUpdateUser;
    }
    
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser;
    }
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
    public String getIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(String isDisabled) {
        this.isDisabled = isDisabled;
    }




}


