package cn.com.sinosoft.usermgr.model;

// Generated 2015-6-1 11:41:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private String id;
	private String orgCode;
	private String loginName;
	private String userName;
	private String comment;
	private String department;
	private String sex;
	private Date birthday;
	private String userType;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String password;
	private String isDisabled;

	public TUser() {
	}

	public TUser(String id, String loginName, String userName, String userType,
			String createUser, Date createTime, String password,
			String isDisabled) {
		this.id = id;
		this.loginName = loginName;
		this.userName = userName;
		this.userType = userType;
		this.createUser = createUser;
		this.createTime = createTime;
		this.password = password;
		this.isDisabled = isDisabled;
	}

	public TUser(String id, String orgCode, String loginName, String userName,
			String comment, String department, String sex, Date birthday,
			String userType, String createUser, Date createTime,
			String updateUser, Date updateTime, String password,
			String isDisabled) {
		this.id = id;
		this.orgCode = orgCode;
		this.loginName = loginName;
		this.userName = userName;
		this.comment = comment;
		this.department = department;
		this.sex = sex;
		this.birthday = birthday;
		this.userType = userType;
		this.createUser = createUser;
		this.createTime = createTime;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.password = password;
		this.isDisabled = isDisabled;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrgCode() {
		return this.orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getIsDisabled() {
		return this.isDisabled;
	}

	public void setIsDisabled(String isDisabled) {
		this.isDisabled = isDisabled;
	}

}
